Quest pokemon form filter
cecpk/RocketMAD pull request #214
Opened 2021-06-08 20:11 UTC by Karl-Parris

## Description
Adds an option to show quest pokemon rewards by form name (eg Galarian, Alolan)

## Motivation and Context
Requested in #rocketmad-general. I would guess the main reasoning would be that people want to be able to find all galarian slowpokes in the current event (but they are flooded with regular ones)

## How Has This Been Tested?
Minimal impact. Just a frontend change that tweaks the functionality of the excludedQuestPokemon filter. Tested combinations of the pokemon filter and this new form filter and all appears to work as expected. Checked it correctly fills settings from store on load, doesn't affect anything when quests or quest filters are turned off.

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/5781373/121250677-e6a62180-c89d-11eb-9297-f837c0e1f3a2.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-06-14 14:48 UTC, ReuschelCGN commented
Tested but Filter didnt work for me. 
Any -> shows all Quest-Mons
Normal -> shows normal Quest-Mons
Galarian -> **dont** show Galarian Porenta (normal Mons are filtered out but galarian not shown)
Alola -> not testet

2021-06-14 15:02 UTC, Karl-Parris commented
> Tested but Filter didnt work for me.
> Any -> shows all Quest-Mons
> Normal -> shows normal Quest-Mons
> Galarian -> **dont** show Galarian Porenta (normal Mons are filtered out but galarian not shown)
> Alola -> not testet

Ah, possibly a translation issue. Guessing your map isn't in English? "Normal" forms actually just have an empty form name, so I guess that would explain why "Normal" and "Any" works fine, but not "Galarian"/"Alola". I will take a look at solutions to this.

2021-06-14 15:42 UTC, ReuschelCGN commented
Yes your right! It is german!

my map.html block looks: 

                      <select id="quest-form-filter">
                        <option value="Any">{{ i18n('Any') }}</option>
                        <option value="Galarian">{{ i18n('Galarian') }}</option>
                        <option value="Alola">{{ i18n('Alola') }}</option>
                        <option value="">{{ i18n('Normal') }}</option>
                      </select>

translation in de.json is right and shown. When I change option value to "Galar" it works as expected.

2021-06-15 13:32 UTC, ReuschelCGN commented
```
<option value="Any">{{ i18n('Any') }}</option>
<option value="{{ i18n('Galarian') }}">{{ i18n('Galarian') }}</option>
<option value="{{ i18n('Alola') }}">{{ i18n('Alola') }}</option>
<option value="">{{ i18n('Normal') }}</option>
```
in map.html works with translation as expected

2021-06-27 16:02 UTC, na-ji requested changes
Thanks for the PR 👍

2021-06-27 16:02 UTC, na-ji commented on static/js/map/map.pokestop.js
> +                (settings.questFormFilter === 'Any' || settings.questFormFilter === getFormName(pokestop.quest.pokemon_id, pokestop.quest.form_id))
`getFormName` returns the translated form name, hence why you need to also translate the select values.

2021-09-03 20:46 UTC, na-ji approved these changes

2021-09-03 20:50 UTC, merged