Slight improvements for MADs "nearby_cells" mode
cecpk/RocketMAD pull request #216
Opened 2021-06-14 23:17 UTC by domizei385

## Description
- group mons around stops when location is not known
- highlight when a location is inaccurate (nearby_cell) or very inaccurate (in L15 cell)
- limit session duration to 3 days, so that session are auto cleaned from redis

## Motivation and Context
better support for @ccev awesome work in MAD

## How Has This Been Tested?
- nothing formal also just ripped this out of a set of other changes, so no guarantees

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-06-25 23:18 UTC, kpresler commented
There's something strange that appears to be going on with this PR where stuff disappears off of my map when it's active.  For example, when I'm running the PR:
![image](https://user-images.githubusercontent.com/12502294/123492452-8aeece80-d5e7-11eb-8199-6b3219dc6ab7.png)


If I switch back to `master`, I don't get spawns spread out, but everything else works about like I'd expect: 

![image](https://user-images.githubusercontent.com/12502294/123492487-9fcb6200-d5e7-11eb-9271-a99a5e957f2a.png)


Aside from confirming that it happens multiple times (ie, switch branch, `npm run build`, restart RM) I've basically not investigated, so this could well be a PEBKAC error.  I _have_ made some (local) changes to `app.py` and `quest.js` to support filtering Quests by region, but at least at first glance I don't see this being related.  Happy to post a diff of those changes if anyone wants, however.

2021-06-26 06:53 UTC, domizei385 commented
Thanks for the feedback.
I have no idea why some gyms would not load for you as I have not touched anything related to that. Did it throw any js exceptions on the console?

2021-06-27 15:41 UTC, na-ji requested changes
Thanks for the PR. However the setting does not work all the time

2021-06-27 15:41 UTC, na-ji commented on static/js/map/map.settings.js
> +            }
Why would you display the S2 Cells with this setting?

2021-06-27 15:41 UTC, na-ji commented on static/js/map/map.settings.js
> +            updateMap({ loadAllPokemon: true })
When toggling on this setting, the Pokémon won't disappear until you reload the page. When toggling off, they will appear right away. 
For this work in both cases,  you will also need to use the `updatePokemons` function.

2021-07-16 07:43 UTC, muckelba commented
Works fine for me, but the two things mentioned by @na-ji are an issue for me too. I just commented the s2cells stuff for now.

2021-09-03 20:43 UTC, na-ji approved these changes

2021-09-03 20:43 UTC, merged